OPENAI_API_KEY="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"

OPENAI_PROJECT_ID="proj_Cg4CjcKLBGkmxSXbXA9yyP4H"
